version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  # app:
  #   build: .
  #   depends_on: 
  #     - mysql
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - JAVA_TOOL_OPTIONS=--add-opens=java.base/java.time=ALL-UNNAMED

