version: '3.8'

services:
  # app:
  #   build: .
  #   depends_on: 
  #     - mysql
  #   ports:
  #     - 8080:8080
  

  mysql:
    container_name: db_midterm
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/docker-entrypoint-initdb.d  



